# Generated by Django 3.0.6 on 2021-03-22 15:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('first_name', models.TextField(max_length=64)),
                ('last_name', models.TextField(max_length=64)),
                ('username', models.TextField(default='user', max_length=64, unique=True)),
                ('phone', models.TextField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('height', models.IntegerField(default=180, null=True)),
                ('weight', models.IntegerField(default=180, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=1)),
                ('user_type', models.IntegerField(choices=[(0, 'Patient'), (1, 'Doctors'), (2, 'Admins')], default=0)),
                ('notes', models.TextField(max_length=800, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('phone', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeCareOf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('risk', models.IntegerField(choices=[(0, 'LOW'), (1, 'MID'), (2, 'HIGH')], default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataPermissionRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_owner', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac_addr', models.TextField(max_length=17)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BelongsToFacilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='having', to='accounts.Facilities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongsto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
