# Generated by Django 3.0.6 on 2020-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Patient'), (1, 'Doctors'), (2, 'Admins')], default=0),
        ),
    ]
