# Generated by Django 3.0.6 on 2020-10-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201013_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=180, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=180, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
